version: '3.8'

services:
  websocket-1:
    build:
      context: .
    container_name: websocket-python-1
    ports:
      - "${SERVER_PORT_1}:${SERVER_PORT_1}"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT_1}
    networks:
      - chat-network
  websocket-2:
    build:
      context: .
    container_name: websocket-python-2
    ports:
      - "${SERVER_PORT_2}:${SERVER_PORT_2}"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT_2}
    networks:
      - chat-network

networks:
  chat-network:
    external: true
